name: FFmpeg Build and Upload Artifacts
on:
  push:
    branches:
      - master
      - main
    tags:
      - "*"
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write
    #
    strategy:
      matrix:
        ffmpeg: ["5.1.2", "5.1.3", "6.0"]
    #
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      #
      - name: Build FFmpeg ${{ matrix.ffmpeg }}
        id: build-ffmpeg
        shell: bash
        run: |
            sh build.sh ${{ matrix.ffmpeg}}
      #
      - name: Upload FFmpeg ${{ matrix.ffmpeg }}
        uses: actions/upload-artifact@v3
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
         name: upload-FFmpeg-${{ matrix.ffmpeg }}
         path: /tmp/bin/ffmpeg-${{matrix.ffmpeg}}.tar
      #
      - name: Release FFmpeg ${{ matrix.ffmpeg }} Nvenc ${{ matrix.nvenc }}
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "# Release ${{github.ref}} \n FFmpeg for 5.12, 5.1.3 & 6.0"
          files: |
            LICENSE
            /tmp/bin/ffmpeg-${{matrix.ffmpeg}}.tar
    #
  #
#